### ISSUE TITLE
Ramdisk issues

### ISSUE THREAD

**Issue by msdx321** [Anik1199/android_device_xiaomi_markw#2]
I think there are problems in your ramdisk files. Might cause a bootloop?
Check this [commit](https://github.com/msdx321/android_device_xiaomi_markw/commit/6310181a53a26ca18691c243347c1cc0c72b668b)
My device tree should be stable enough.

**Comment by msdx321** [comment]
Espically the init.qcom.usb.rc

**Comment by Anik1199** [comment]
Yeah just flashed a build and have that issue. Can we talk in some chat client like telegram?
If you wanna then ping me https://t.me/Anik1199

**Comment by Anik1199** [comment]
Well i got a black display after bootanimation

**Comment by Anik1199** [comment]
Now ramdisk issue is fixed.
